baseURL = 'https://qwarnant.com'
languageCode = 'en-us'
title = 'Quentin Warnant - Senior Rendering Engineer'
theme = 'blowfish'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']

[caches]
  [caches.images]
    dir = ':cacheDir/images'